inherit_from: .rubocop_todo.yml
require: rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'let']

RSpec/NestedGroups:
  Max: 8

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and
    - while

RSpec/DescribeClass:
  Enabled: false
